### ISSUE TITLE
undefined method 'ogp'

### ISSUE THREAD

**Issue by mrtnpro** [ngs/middleman-ogp#2]
Hi there,

i can't get your extension to work. As soon as I add the following code to my 'config.rb' my middleman crashes:

```
activate :ogp do |ogp|
  ## Default Properties
  ogp.namespaces = {
    fb: data.ogp.fb,
    # from data/ogp/fb.yml
    og: data.ogp.og
    # from data/ogp/og.yml
  }
  ## Base URL for og:url
  og.base_url = 'http://domain.tld/'
end
```

Resulting in following error:

```
Error reloading Middleman: undefined method `ogp' for #<Middleman::CoreExtensions::Data::DataStore:0x007fc40c31b870>
/Users/martin/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/middleman-core-3.2.2/lib/middleman-core/core_extensions/data.rb:177:in `method_missing'
/Users/martin/.middleman/middleboy-pure/config.rb:53:in `block in initialize'
/Users/martin/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/middleman-core-3.2.2/lib/middleman-core/extensions.rb:199:in `setup_options'
/Users/martin/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/middleman-core-3.2.2/lib/middleman-core/extensions.rb:172:in `initialize'
/Users/martin/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/middleman-core-3.2.2/lib/middleman-core/core_extensions/extensions.rb:122:in `new'
/Users/martin/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/middleman-core-3.2.2/lib/middleman-core/core_extensions/extensions.rb:122:in `activate'
/Users/martin/.middleman/middleboy-pure/config.rb:50:in `initialize'
/Users/martin/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/middleman-core-3.2.2/lib/middleman-core/core_extensions/extensions.rb:162:in `instance_eval'
/Users/martin/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/middleman-core-3.2.2/lib/middleman-core/core_extensions/extensions.rb:162:in `initialize'
/Users/martin/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/middleman-core-3.2.2/lib/middleman-core/core_extensions/data.rb:35:in `initialize'
/Users/martin/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/middleman-core-3.2.2/lib/middleman-core/application.rb:184:in `initialize'
/Users/martin/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/middleman-core-3.2.2/lib/middleman-core/core_extensions/request.rb:52:in `new'
/Users/martin/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/middleman-core-3.2.2/lib/middleman-core/core_extensions/request.rb:52:in `inst'
/Users/martin/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/middleman-core-3.2.2/lib/middleman-core/preview_server.rb:103:in `new_app'
/Users/martin/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/middleman-core-3.2.2/lib/middleman-core/preview_server.rb:72:in `reload'
/Users/martin/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/middleman-core-3.2.2/lib/middleman-core/preview_server.rb:44:in `block in start'
/Users/martin/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/middleman-core-3.2.2/lib/middleman-core/preview_server.rb:35:in `loop'
/Users/martin/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/middleman-core-3.2.2/lib/middleman-core/preview_server.rb:35:in `start'
/Users/martin/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/middleman-core-3.2.2/lib/middleman-core/cli/server.rb:79:in `server'
/Users/martin/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
/Users/martin/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
/Users/martin/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
/Users/martin/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
/Users/martin/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/middleman-core-3.2.2/lib/middleman-core/cli.rb:77:in `method_missing'
/Users/martin/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/thor-0.19.1/lib/thor/command.rb:29:in `run'
/Users/martin/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/thor-0.19.1/lib/thor/command.rb:126:in `run'
/Users/martin/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
/Users/martin/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
/Users/martin/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
/Users/martin/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/middleman-core-3.2.2/lib/middleman-core/cli.rb:22:in `start'
/Users/martin/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/middleman-core-3.2.2/bin/middleman:18:in `<top (required)>'
/Users/martin/.rbenv/versions/1.9.3-p194/bin/middleman:23:in `load'
/Users/martin/.rbenv/versions/1.9.3-p194/bin/middleman:23:in `<main>'
```

Am I missing something?

**Comment by andreamoro** [comment]
Adding the files in ./data/ogp solve the compilation issues, but there is still a problem with the output. In my case I can't see anything rendered in the HTML.
